### ISSUE TITLE
Cannot make Experiment 1 to work

### ISSUE THREAD

**Issue by eadward** [AngelSensorCommunityEdition/angel-sdk-community#9]
Dear all,
I am trying to connect my AngelSensor to a Windows PC using this community's examples. and a BlueGiga BLE112 dongle, but I am facing two problems:

1) I can only activate the AngelSensor (which I tested using the app) if connected to USB. I cannot activate it otherwise

2) I tried Experiment 1 (using the command `python main.py -a 00:07:80:78:ca:a3`) and I get the following error:

```bash
Reset BLED112
Connecting to A3:CA:78:80:07:00
BLED112 thread started
Enumerating Heart Rate Service
Disconnected
Traceback (most recent call last):
  File "main.py", line 266, in <module>
    main()
  File "main.py", line 256, in main
    hrHandle = SubscribeToHeartRateProcedure(ble).run()
  File "main.py", line 207, in run
    groups = self.ble.readByGroupType(1, 0xFFFF, Uint16(int(GATT_PRIMARY_SERVICE
,16)).serialize())
B  File "main.py", line 185, in readByGroupType
LED112 thread stopped
self.completeProcedure()
  File "main.py", line 155, in completeProcedure
    msg = self.waitRemote(AttClientProcedureCompleted())
  File "main.py", line 127, in waitRemote
    if not msg: raise BleRemoteTimeout()
__main__.BleRemoteTimeout
```

Can anybody help with this issue? thank you in advance.

All the best,
Eduardo.

**Comment by eadward** [comment]
Is it possible that the AngelSensors are actually the problem? I really cannot activate them without connecting to a USB port in a computer ... Anybody faced similar issues?
